name: docker

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - build
      - Dockerfile

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v3

    - uses: docker/setup-qemu-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        image_tag="ghcr.io/${{ github.repository }}:${{ github.run_id }}"
        image_latest="ghcr.io/${{ github.repository }}:latest"
        ./build \
          --platform linux/amd64,linux/arm64 \
          --tag "$image_tag" \
          --tag "$image_latest" \
          --push

        echo "Use custom image:" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "    nextstrain build --docker --image=$image_tag" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "or" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "    nextstrain shell --docker --image=$image_tag" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
