name: docker

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - build
      - Dockerfile

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        image_tag="ghcr.io/${{ github.repository }}:${{ github.run_id }}"
        image_latest="ghcr.io/${{ github.repository }}:latest"
        ./build \
          --platform linux/amd64 \
          --tag "$image_tag" \
          --tag "$image_latest" \
          --push

        cat >"$GITHUB_STEP_SUMMARY" <<~~
        Image successfully published!

        Use with the --image option in Nextstrain CLI:

            nextstrain build --docker --image=$image_tag .

        or as an environment variable:

            export NEXTSTRAIN_DOCKER_IMAGE=$image_tag
            nextstrain build .
        ~~
