name: docker

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - build
      - Dockerfile

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        ./build \
          --platform linux/amd64,linux/arm64 \
          --tag "ghcr.io/${{ github.repository }}:${{ github.run_id }}" \
          --tag "ghcr.io/${{ github.repository }}:latest" \
          --push
